language: python

dist: trusty

script: py.test tests.py

install: pip install lorem jupyter beautifulsoup4 lxml pandas  \
                     progressbar2 dask toolz pandas_datareader \
                     tables cloudpickle toyplot xlwt pyspark   \
                     fastparquet pyarrow

cache: pip
cache: ccache

python:
  - 3.6
