name: big-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas
  - lorem 
  - joblib 
  - ujson
  - dask
  - pyspark
  - graphviz
  - python-graphviz
  - beautifulsoup4
