name: big-data
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - pandas
  - lorem 
  - joblib 
  - ujson
  - dask
  - pytables
  - java-jdk
  - pyspark
  - java-jdk
  - graphviz
  - python-graphviz
  - beautifulsoup4
  - toolz 
  - h5py 
  - partd
  - matplotlib
  - seaborn
  - hdfs3
  - progressbar2
  - pyarrow
  - feather-format
  - fastparquet
  - distributed
  - pip
  - pip:
    - loky
    - toyplot
